/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * runtest开发接口文档 Web端网站 - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Dept.delete_api_dept_delete': ['DELETE', '/api/Dept/Delete'],
  'Dept.get_api_dept_getinfo': ['GET', '/api/Dept/GetInfo'],
  'Dept.get_api_dept_gettree': ['GET', '/api/Dept/GetTree'],
  'Dept.get_api_dept_gettreeselect': ['GET', '/api/Dept/GetTreeSelect'],
  'Dept.put_api_dept_setstatus': ['PUT', '/api/Dept/SetStatus'],
  'Dept.post_api_dept_submit': ['POST', '/api/Dept/Submit'],
  'DicData.get_api_dicdata_getallgroupby': ['GET', '/api/DicData/GetAllGroupBy'],
  'DicData.get_api_dicdata_getselect': ['GET', '/api/DicData/GetSelect'],
  'Login.get_api_login_info': ['GET', '/api/Login/Info'],
  'Login.post_api_login_login': ['POST', '/api/Login/Login'],
  'Login.post_api_login_loginout': ['POST', '/api/Login/LoginOut'],
  'Menu.delete_api_menu_delete': ['DELETE', '/api/Menu/Delete'],
  'Menu.get_api_menu_getbyroleid': ['GET', '/api/Menu/GetByRoleId'],
  'Menu.get_api_menu_getinfo': ['GET', '/api/Menu/GetInfo'],
  'Menu.get_api_menu_getroutes': ['GET', '/api/Menu/GetRoutes'],
  'Menu.get_api_menu_gettree': ['GET', '/api/Menu/GetTree'],
  'Menu.get_api_menu_gettreeselect': ['GET', '/api/Menu/GetTreeSelect'],
  'Menu.get_api_menu_select': ['GET', '/api/Menu/Select'],
  'Menu.post_api_menu_setbyroleid': ['POST', '/api/Menu/SetByRoleId'],
  'Menu.put_api_menu_setstatus': ['PUT', '/api/Menu/SetStatus'],
  'Menu.post_api_menu_submit': ['POST', '/api/Menu/Submit'],
  'Role.delete_api_role_delete': ['DELETE', '/api/Role/Delete'],
  'Role.get_api_role_getinfo': ['GET', '/api/Role/GetInfo'],
  'Role.get_api_role_getpage': ['GET', '/api/Role/GetPage'],
  'Role.get_api_role_getselect': ['GET', '/api/Role/GetSelect'],
  'Role.put_api_role_setstatus': ['PUT', '/api/Role/SetStatus'],
  'Role.post_api_role_submit': ['POST', '/api/Role/Submit'],
  'TableColumn.delete_api_tablecolumn_delete_tableof': ['DELETE', '/api/TableColumn/Delete/{tableof}'],
  'TableColumn.get_api_tablecolumn_getform_tableof': ['GET', '/api/TableColumn/GetForm/{tableof}'],
  'TableColumn.post_api_tablecolumn_submit_tableof': ['POST', '/api/TableColumn/Submit/{tableof}'],
  'TableView.delete_api_tableview_delete': ['DELETE', '/api/TableView/Delete'],
  'TableView.delete_api_tableview_deletetableheader': ['DELETE', '/api/TableView/DeleteTableHeader'],
  'TableView.get_api_tableview_gettableheader': ['GET', '/api/TableView/GetTableHeader'],
  'TableView.get_api_tableview_getview': ['GET', '/api/TableView/GetView'],
  'TableView.get_api_tableview_page': ['GET', '/api/TableView/Page'],
  'TableView.put_api_tableview_settableheader': ['PUT', '/api/TableView/SetTableHeader'],
  'TableView.put_api_tableview_settablesort': ['PUT', '/api/TableView/SetTableSort'],
  'TableView.post_api_tableview_submit': ['POST', '/api/TableView/Submit'],
  'Upload.post_api_upload_images': ['POST', '/api/Upload/Images'],
  'User.delete_api_user_delete': ['DELETE', '/api/User/Delete'],
  'User.get_api_user_getinfo': ['GET', '/api/User/GetInfo'],
  'User.get_api_user_getpage': ['GET', '/api/User/GetPage'],
  'User.put_api_user_setstatus': ['PUT', '/api/User/SetStatus'],
  'User.post_api_user_submit': ['POST', '/api/User/Submit']
};
